version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ..:/app
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
